### ISSUE TITLE
[BUG] :  ROS2 윈도우 설치과정 오류2

### ISSUE THREAD

**Issue by sinnara2021** [Road-Balance/gcamp_ros2_basic#15]
# **ROS2 윈도우 설치법**
실행한 프로그램 및 커멘드 라인 / 예상한 결과 / 문제 상황 / 시도해본 내용 (스크린샷이 있을 시 첨부하면 더욱 좋습니다.)

## **To Reproduce 실행한 프로그램 및 커멘드 라인**

1. powershell 에서 chocolatey 설치 확인함.
![image](https://user-images.githubusercontent.com/79739569/155289431-0ba54fa0-576d-4c93-b561-067162ee65a6.png)

2. powershell 에서 Windows Terminal 이 설치 되지 않아 수동으로 설치함.
![image](https://user-images.githubusercontent.com/79739569/155289893-e247c1bf-13f4-4a90-815c-f77291f46df7.png)
![image](https://user-images.githubusercontent.com/79739569/155290461-9b318732-8a0f-4bdc-a1a7-0e208bc9bfad.png)
![image](https://user-images.githubusercontent.com/79739569/155290497-25680728-94f7-46da-bd89-9763cbe0cc3b.png)

3.python 버젼이 상위 버젼 3.10이 설치 되어 있어 버젼다운 하여 다시 설치함.
![image](https://user-images.githubusercontent.com/79739569/155291178-5cbb5f67-2735-4217-9ab3-d9b7ff37647b.png)
![image](https://user-images.githubusercontent.com/79739569/155291536-392df7a9-2ba9-44a1-8bf5-ae06795b2bc5.png)
좀 이상하긴 하지만. python 3.8.3 버젼 설치됨.
![image](https://user-images.githubusercontent.com/79739569/155291914-8792d9c0-ec6d-400a-8e66-fcfb3630c450.png)
![image](https://user-images.githubusercontent.com/79739569/155292109-3facaae3-79d0-42be-b515-8b6bb5dc0677.png)

4. git 설치 확인함.
![image](https://user-images.githubusercontent.com/79739569/155292193-a90b4436-e55a-473f-b6e7-9e56fb34f407.png)
![image](https://user-images.githubusercontent.com/79739569/155292245-b153c08e-0550-4024-b010-128cfa0f46a7.png)

5. C++ 다운
![image](https://user-images.githubusercontent.com/79739569/155292917-8122e47b-161d-44ba-a3b8-ef791589467e.png)

checksum 업그레이드 하라 해서...다음과 같이 실행함. 엄청 머가 오래동안 설치 됨
> choco upgrade all --force
![image](https://user-images.githubusercontent.com/79739569/155293496-7eb62207-3a61-4688-afd8-00f3ca1a5de6.png)
![image](https://user-images.githubusercontent.com/79739569/155293851-ccc09816-d3d9-4473-941b-f912fcc6f868.png)
![image](https://user-images.githubusercontent.com/79739569/155293986-584f3ec5-aaa7-4027-a4d7-2c37112581b0.png)
![image](https://user-images.githubusercontent.com/79739569/155294106-94d360e0-115d-4e96-b282-93a69ed88c42.png)

좀 이상해서 설치 그만 할라다가 다 필요한것도 같아서 계속 'y' 눌러서 설치 진행함.
![image](https://user-images.githubusercontent.com/79739569/155294967-529597bb-d779-4e3a-b97a-fc2d56c803e9.png)
![image](https://user-images.githubusercontent.com/79739569/155297335-f28e75db-168d-4cd7-a243-ac3de9057234.png)
막 자꾸 깔리고 설치됨... ros2 foxy 같아서 그냥 둠.

![image](https://user-images.githubusercontent.com/79739569/155300572-ae8f0012-6cd7-4cd2-a9d4-df00599ec364.png)
에러 2개가 뜨지만 설치는 된거 같아요.

6. OpenSSL 설치.
![image](https://user-images.githubusercontent.com/79739569/155300842-a39fe7a7-90ec-4d14-a3e4-54a4ec3f70a2.png)
![image](https://user-images.githubusercontent.com/79739569/155300977-f3807fb0-b264-43e0-82c9-2467044e2557.png)
설치되어 있음.

7. C:\Program Files\OpenSSL-Win64\bin\openssl.cfg 환경변수 추가되어 있음.
![image](https://user-images.githubusercontent.com/79739569/155301317-086e57ca-69f0-4aff-8e52-44e37782165e.png)

8.Visual Studio 2019 설치되어 있음.
![image](https://user-images.githubusercontent.com/79739569/155301733-383d46ab-5e46-4804-a67b-1cc3d59bd6c6.png)

9.CMake 설치 및 환경변수 추가.
![image](https://user-images.githubusercontent.com/79739569/155301916-c16888f6-3fdb-4b35-8f17-e4ab7732da43.png)
![image](https://user-images.githubusercontent.com/79739569/155302025-e0883e11-36de-4b72-9dfa-6a1177788008.png)

10. nuget package 설치.
![image](https://user-images.githubusercontent.com/79739569/155302347-3fcf6d2e-c9e8-4fd2-b97d-5f97c6d06213.png)
![image](https://user-images.githubusercontent.com/79739569/155302527-fd63c3da-148b-417d-b469-f612d183ced4.png)
이미 다 설치 되어 있다는 뜻 같다고 추측함.

11. PYTHON 패키지 설치.
![image](https://user-images.githubusercontent.com/79739569/155303253-be0e1dca-a86e-442a-bca8-0644df98be1b.png)

12. Graphviz 설치.
![image](https://user-images.githubusercontent.com/79739569/155303359-5e641e06-fff2-43e9-a805-b416eeee2e54.png)

13. OpenCV 3.4.6 설치. 환경변수 추가.
![image](https://user-images.githubusercontent.com/79739569/155303529-8638b896-c218-4a51-ba36-7bd58a4af37f.png)
![image](https://user-images.githubusercontent.com/79739569/155303766-31812019-9bb8-4e72-9d76-3ce31f876cba.png)
![image](https://user-images.githubusercontent.com/79739569/155303822-addaefe6-99a2-446b-9449-e5671064f326.png)

14. Install ROS
![image](https://user-images.githubusercontent.com/79739569/155303998-27eecdad-5074-4748-abc6-0cbaed08c45a.png)

15. 재부팅하러 감.

16. workspace 생성 후 colcon build
x64 Native Tools Command
![image](https://user-images.githubusercontent.com/79739569/155321739-3946339b-ef3b-49ee-a813-da1904cb340b.png)
![image](https://user-images.githubusercontent.com/79739569/155322122-90474233-eb91-4c5a-8995-9b9c64607f3e.png)
gcamp_gazebo 파일이 또 있다고 떠서..  gcamp_ros2_basic\gcamp_gazebo 파일 삭제함.(gcamp_ros2_basic 폴더 자체 다 삭제함. )
![image](https://user-images.githubusercontent.com/79739569/155322625-efc71674-685f-4587-8d04-42b64421a398.png)
환경 변수가 없다고 떠서 환경변수 추가함.(C:\opt\ros\foxy\x64\tools\vcpkg\installed\x64-windows)
![image](https://user-images.githubusercontent.com/79739569/155322822-39a9d1e6-98bf-46ce-bb05-4b5c3e1654a7.png)
![image](https://user-images.githubusercontent.com/79739569/155323178-bf65bdfb-adf4-4073-84b3-a38158b12b68.png)
추가해도 환경변수 뜨는 에러 뜨는 현상은 같음.
**** 환경변수 에러 이유 모르겠음.******* 그냥 넘어감.
![image](https://user-images.githubusercontent.com/79739569/155323619-c304205d-4a2f-4b3f-9439-ee84fdbbe43c.png)

17. uuidgen 코드 기록
![image](https://user-images.githubusercontent.com/79739569/155324101-5d2f4442-52ba-443c-a26a-909fa34418c8.png)
![image](https://user-images.githubusercontent.com/79739569/155324663-f90d7402-ae05-4891-9255-c905be22325c.png)
ros2 터미널 생성됨.
![image](https://user-images.githubusercontent.com/79739569/155325002-2dbcae12-a02a-495b-9df4-95745d29f6ca.png)

18. Gazebo 환경 Setup
![image](https://user-images.githubusercontent.com/79739569/155325269-723f1cd8-9a5a-4ccd-a783-0fa9d3e3faa3.png)
![image](https://user-images.githubusercontent.com/79739569/155325411-f4395dd1-1ec6-4dbe-bca7-69344a2bfb9b.png)
--------------------------------------------------------------------------------------------------
> colcon build --symlink-install --packages-select py_service_pkg
에러발생...
![image](https://user-images.githubusercontent.com/79739569/155325520-fb95bbc9-4482-4e47-88dd-78078279434d.png)
-------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/79739569/155325790-e0c1fed5-9388-422e-a2ac-83d6b45b563e.png)

![image](https://user-images.githubusercontent.com/79739569/155325952-1732742e-ce1d-40dc-96e8-769dff7339e8.png)

install 폴더 내 위치한 파일들 중 setup.bat이 존재함!!!! 이제 생겼어요!!!

19. 데모실행...
> ros2 launch gcamp_gazebo gcamp_world_windows.launch.py
![image](https://user-images.githubusercontent.com/79739569/155326134-cdd9ade6-3b2f-454d-9e00-d5e6879602c9.png)
연결할 프로그램 선택하라고 뜸.
머 해야 할지 몰라..아래와 같이 선택함.
![image](https://user-images.githubusercontent.com/79739569/155326219-c5f6ffdf-a4df-4af3-b3a9-399dd46b59aa.png)
![image](https://user-images.githubusercontent.com/79739569/155327456-cb2d724f-4820-4541-8554-ea6873e2a606.png)

## **Expected behavior 예상한 결과**
ROS2 실행이 되지 않아요. 머가 어디서 안된건지? 진짜 못찾겠습니다. ㅠ.ㅠ

## **Environment 사용환경**
 - OS Version : Windows 10 Home
 - ROS Version : ROS2

## **Relevant log output (관련 로그 output을 적어주세요)**
16.workspace 생성 후 colcon build 에서 환경변수 에러가 있었는데 이부분이 잘못된거 같아요.

### **충분한 리서치 없이 무분별한 Issue는 삭제됩니다.**
이슈를 만들기 전에...
- [ ] 구글링을 통해 충분한 검색을 해보았다. *
- [ ] Repo내 같은 이슈가 존재하는지 확인해 보았다. *
- [ ] 문제 해결을 위해 이슈에 충분한 정보를 제공하였다. *

**Comment by sinnara2021** [comment]
저 또 일하러 가야 해서. 다시 작업하러 오겠습니다. 오늘은 봐야죠. ROS가 먼지...^^

**Comment by sinnara2021** [comment]
진짜 이제 모르겠어요...ㅠ.ㅠ 도와주세용.

**Comment by sinnara2021** [comment]
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.10
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************

C:\gcamp_ros2_ws>c:\opt\ros\foxy\x64\setup.bat

C:\gcamp_ros2_ws>ros2 launch gcamp_gazebo gcamp_world_windows.launch.py
[INFO] [launch]: All log files can be found below C:\Users\tlssk\.ros\log\2022-02-23-22-37-28-035304-DESKTOP-IH8GP6F-10944
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at c:\opt\ros\foxy\x64\lib\site-packages\launch\launch_service.py:226> exception=PackageNotFoundError("package 'py_service_pkg' not found, searching: ['c:\\\\gcamp_ros2_ws\\\\install\\\\gcamp_gazebo', 'c:\\\\opt\\\\ros\\\\foxy\\\\x64']")>
Traceback (most recent call last):
  File "c:\opt\ros\foxy\x64\lib\site-packages\ament_index_python\packages.py", line 50, in get_package_prefix
    content, package_prefix = get_resource('packages', package_name)
  File "c:\opt\ros\foxy\x64\lib\site-packages\ament_index_python\resources.py", line 48, in get_resource
    raise LookupError(
LookupError: Could not find the resource 'py_service_pkg' of type 'packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\utilities\visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\utilities\visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\utilities\visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  [Previous line repeated 1 more time]
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\utilities\visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\action.py", line 108, in visit
    return self.execute(context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch_ros\actions\node.py", line 431, in execute
    ret = super().execute(context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\actions\execute_process.py", line 823, in execute
    self.__expand_substitutions(context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\actions\execute_process.py", line 668, in __expand_substitutions
    cmd = [perform_substitutions(context, x) for x in self.__cmd]
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\actions\execute_process.py", line 668, in <listcomp>
    cmd = [perform_substitutions(context, x) for x in self.__cmd]
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\utilities\perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\utilities\perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\launch_context.py", line 197, in perform_substitution
    return substitution.perform(self)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch_ros\substitutions\executable_in_package.py", line 76, in perform
    package_prefix = super().perform(context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch_ros\substitutions\find_package.py", line 79, in perform
    result = self.find(package)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch_ros\substitutions\find_package.py", line 96, in find
    return get_package_prefix(package_name)
  File "c:\opt\ros\foxy\x64\lib\site-packages\ament_index_python\packages.py", line 52, in get_package_prefix
    raise PackageNotFoundError(
ament_index_python.packages.PackageNotFoundError: "package 'py_service_pkg' not found, searching: ['c:\\\\gcamp_ros2_ws\\\\install\\\\gcamp_gazebo', 'c:\\\\opt\\\\ros\\\\foxy\\\\x64']"
Task exception was never retrieved
future: <Task finished name='Task-16' coro=<LaunchService._process_one_event() done, defined at c:\opt\ros\foxy\x64\lib\site-packages\launch\launch_service.py:226> exception=RuntimeError('Signal event received before subprocess transport available.')>
Traceback (most recent call last):
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\utilities\visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\action.py", line 108, in visit
    return self.execute(context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\actions\opaque_function.py", line 75, in execute
    return self.__function(context, *self.__args, **self.__kwargs)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\actions\execute_process.py", line 443, in __on_signal_process_event    raise RuntimeError('Signal event received before subprocess transport available.')
RuntimeError: Signal event received before subprocess transport available.
[INFO] [gzserver-1]: process started with pid [13896]
[INFO] [gzclient   -2]: process started with pid [37564]
[INFO] [ros2-3]: process started with pid [38392]
[WARNING] [gzclient   -2]: 'SIGINT' sent to process[gzclient   -2] not supported on Windows, escalating to 'SIGTERM'
[INFO] [gzclient   -2]: sending signal 'SIGTERM' to process[gzclient   -2]
[WARNING] [gzserver-1]: 'SIGINT' sent to process[gzserver-1] not supported on Windows, escalating to 'SIGTERM'
[INFO] [gzserver-1]: sending signal 'SIGTERM' to process[gzserver-1]
[ERROR] [gzserver-1]: process has died [pid 13896, exit code 1, cmd 'gzserver c:\gcamp_ros2_ws\install\gcamp_gazebo\share\gcamp_gazebo\worlds\bocbot_office.world                                                                      -s libgazebo_ros_init.so   -s libgazebo_ros_factory.so   -s libgazebo_ros_force_system.so       '].
[ERROR] [gzclient   -2]: process has died [pid 37564, exit code 1, cmd 'gzclient   '].
[ERROR] [ros2-3]: process[ros2-3] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [ros2-3]: sending signal 'SIGTERM' to process[ros2-3]
[ERROR] [ros2-3]: process has died [pid 38392, exit code 1, cmd 'ros2 param set /gazebo use_sim_time True'].

C:\gcamp_ros2_ws>

**Comment by sinnara2021** [comment]
다시 실행해봤는데 .. 요런 에러 코드가 떠서 공유합니다.

**Comment by kimsooyoung** [comment]
모든 로그들을 확인하였습니다. 

colcon build가 실패한 것이 가장 큰 원인이라고 생각되는데요.
저도 시도해 본 결과 

1. colcon build 시 windows terminal을 관리자 권한으로 실행하시고
2. 환경 변수 설정 시 오류가 생긴 것은 맞아보입니다. 이는 제 강의의 환경 변수를 그대로 사용치 마시고, 영상을 확인하신 뒤 @sinnara2021 님의 PC 위치와 맞추어 다시 한 번 확인들을 부탁드립니다.

아무래도 이것저것 절차들이 많다 보니 제 환경에서 상황을 온전히 구현하는 것이 불가능에 가까운 것 같습니다.\

그래도 설치들은 모두 완료되었고 몇가지 이슈만 잡으면 되는 상황이니 화이팅입니다!!

**Comment by sinnara2021** [comment]
경로는 저도 제 PC 경로로 맞추어서 셋팅하긴 했습니다. 음 위에 보면 환경변수 에 다 제 경로구요.

**Comment by sinnara2021** [comment]
![image](https://user-images.githubusercontent.com/79739569/155654756-c094a8cf-137b-4269-8ed4-9682242dcf33.png)
가제보 관련 셋팅 되어 있습니다.

**Comment by kimsooyoung** [comment]
> 가제보 관련 셋팅 되어 있습니다.

제가 조언드린 내용대로 해보셨는지, 그래도 안된다면 에러 로그는 어떻게 바뀌었는지 알려주시기 바랍니다.

Gazebo 폴더를 캡쳐해서 보여주신다고 해서 제가 원인을 바로 알 수가 없습니다... 
초반 글과 같이 캡쳐와 함께 설명을 부탁드립니다.

더불어 Issue 제목도 수정 부탁드립니다.

**Comment by sinnara2021** [comment]
![image](https://user-images.githubusercontent.com/79739569/155661501-8dbef4a7-da90-4080-bc1c-84c71e368d0d.png)

**Comment by sinnara2021** [comment]
> > 가제보 관련 셋팅 되어 있습니다.
> 
> 제가 조언드린 내용대로 해보셨는지, 그래도 안된다면 에러 로그는 어떻게 바뀌었는지 알려주시기 바랍니다.
> 
> Gazebo 폴더를 캡쳐해서 보여주신다고 해서 제가 원인을 바로 알 수가 없습니다... 초반 글과 같이 캡쳐와 함께 설명을 부탁드립니다.
> 
> 더불어 Issue 제목도 수정 부탁드립니다.

**Comment by sinnara2021** [comment]
제가 추측하는건... 왜 된건지 모르겠는데요. 중복되는 환경변수를 좀 지웠어요

**Comment by sinnara2021** [comment]
근데 에러는 떴어요.. 이 에러는 먼지 모르겠네요.
C:\gcamp_ros2_ws>colcon build --symlink-install --packages-select gcamp_gazebo
[1.953s] root DEBUG Using proactor: IocpProactor
Starting >>> gcamp_gazebo
[1.986s] colcon.colcon_ros.prefix_path.catkin WARNING The path 'C:\opt\ros\foxy\x64\tools\vcpkg\installed\x64-windows' in the environment variable CMAKE_PREFIX_PATH doesn't exist
Finished <<< gcamp_gazebo [9.80s]

Summary: 1 package finished [10.2s]

C:\gcamp_ros2_ws> ros2 launch gcamp_gazebo gcamp_world_windows.launch.py
[INFO] [launch]: All log files can be found below C:\Users\tlssk\.ros\log\2022-02-25-14-48-14-313066-DESKTOP-IH8GP6F-27864
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at c:\opt\ros\foxy\x64\lib\site-packages\launch\launch_service.py:226> exception=PackageNotFoundError("package 'py_service_pkg' not found, searching: ['c:\\\\gcamp_ros2_ws\\\\install\\\\gcamp_gazebo', 'c:\\\\gcamp_ros2_ws\\\\install\\\\custom_interfaces', 'c:\\\\opt\\\\ros\\\\foxy\\\\x64']")>
Traceback (most recent call last):
  File "c:\opt\ros\foxy\x64\lib\site-packages\ament_index_python\packages.py", line 50, in get_package_prefix
    content, package_prefix = get_resource('packages', package_name)
  File "c:\opt\ros\foxy\x64\lib\site-packages\ament_index_python\resources.py", line 48, in get_resource
    raise LookupError(
LookupError: Could not find the resource 'py_service_pkg' of type 'packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\utilities\visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\utilities\visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\utilities\visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  [Previous line repeated 1 more time]
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\utilities\visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\action.py", line 108, in visit
    return self.execute(context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch_ros\actions\node.py", line 431, in execute
    ret = super().execute(context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\actions\execute_process.py", line 823, in execute
    self.__expand_substitutions(context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\actions\execute_process.py", line 668, in __expand_substitutions
    cmd = [perform_substitutions(context, x) for x in self.__cmd]
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\actions\execute_process.py", line 668, in <listcomp>
    cmd = [perform_substitutions(context, x) for x in self.__cmd]
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\utilities\perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\utilities\perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\launch_context.py", line 197, in perform_substitution
    return substitution.perform(self)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch_ros\substitutions\executable_in_package.py", line 76, in perform
    package_prefix = super().perform(context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch_ros\substitutions\find_package.py", line 79, in perform
    result = self.find(package)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch_ros\substitutions\find_package.py", line 96, in find
    return get_package_prefix(package_name)
  File "c:\opt\ros\foxy\x64\lib\site-packages\ament_index_python\packages.py", line 52, in get_package_prefix
    raise PackageNotFoundError(
ament_index_python.packages.PackageNotFoundError: "package 'py_service_pkg' not found, searching: ['c:\\\\gcamp_ros2_ws\\\\install\\\\gcamp_gazebo', 'c:\\\\gcamp_ros2_ws\\\\install\\\\custom_interfaces', 'c:\\\\opt\\\\ros\\\\foxy\\\\x64']"
Task exception was never retrieved
future: <Task finished name='Task-16' coro=<LaunchService._process_one_event() done, defined at c:\opt\ros\foxy\x64\lib\site-packages\launch\launch_service.py:226> exception=RuntimeError('Signal event received before subprocess transport available.')>
Traceback (most recent call last):
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\utilities\visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\action.py", line 108, in visit
    return self.execute(context)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\actions\opaque_function.py", line 75, in execute
    return self.__function(context, *self.__args, **self.__kwargs)
  File "c:\opt\ros\foxy\x64\lib\site-packages\launch\actions\execute_process.py", line 443, in __on_signal_process_event
    raise RuntimeError('Signal event received before subprocess transport available.')
RuntimeError: Signal event received before subprocess transport available.
[INFO] [gzserver-1]: process started with pid [19712]
[INFO] [gzclient   -2]: process started with pid [17360]
[INFO] [ros2-3]: process started with pid [2852]
[WARNING] [gzclient   -2]: 'SIGINT' sent to process[gzclient   -2] not supported on Windows, escalating to 'SIGTERM'
[INFO] [gzclient   -2]: sending signal 'SIGTERM' to process[gzclient   -2]
[WARNING] [gzserver-1]: 'SIGINT' sent to process[gzserver-1] not supported on Windows, escalating to 'SIGTERM'
[INFO] [gzserver-1]: sending signal 'SIGTERM' to process[gzserver-1]
[ERROR] [gzclient   -2]: process has died [pid 17360, exit code 1, cmd 'gzclient   '].
[ERROR] [gzserver-1]: process has died [pid 19712, exit code 1, cmd 'gzserver c:\gcamp_ros2_ws\install\gcamp_gazebo\share\gcamp_gazebo\worlds\bocbot_office.world                                                                      -s libgazebo_ros_init.so   -s libgazebo_ros_factory.so   -s libgazebo_ros_force_system.so       '].
[ERROR] [ros2-3]: process[ros2-3] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [ros2-3]: sending signal 'SIGTERM' to process[ros2-3]
[ERROR] [ros2-3]: process has died [pid 2852, exit code 1, cmd 'ros2 param set /gazebo use_sim_time True'].

C:\gcamp_ros2_ws>

**Comment by sinnara2021** [comment]
'C:\opt\ros\foxy\x64\tools\vcpkg\installed\x64-windows' in the environment variable CMAKE_PREFIX_PATH doesn't exist
환경 변수 추가 했는데 왜 자꾸 이런 에러가 뜨는걸까요?

**Comment by sinnara2021** [comment]
[ERROR] [gzclient   -2]: process has died [pid 17360, exit code 1, cmd 'gzclient   '].
[ERROR] [gzserver-1]: process has died [pid 19712, exit code 1, cmd 'gzserver c:\gcamp_ros2_ws\install\gcamp_gazebo\share\gcamp_gazebo\worlds\bocbot_office.world                                                                      -s libgazebo_ros_init.so   -s libgazebo_ros_factory.so   -s libgazebo_ros_force_system.so       '].
[ERROR] [ros2-3]: process[ros2-3] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [ros2-3]: sending signal 'SIGTERM' to process[ros2-3]
[ERROR] [ros2-3]: process has died [pid 2852, exit code 1, cmd 'ros2 param set /gazebo use_sim_time True'].

체크 해봐야 할 에러 항목들이에요..

**Comment by sinnara2021** [comment]
> 



> > > 가제보 관련 셋팅 되어 있습니다.
> > 
> > 
> > 제가 조언드린 내용대로 해보셨는지, 그래도 안된다면 에러 로그는 어떻게 바뀌었는지 알려주시기 바랍니다.
> > Gazebo 폴더를 캡쳐해서 보여주신다고 해서 제가 원인을 바로 알 수가 없습니다... 초반 글과 같이 캡쳐와 함께 설명을 부탁드립니다.
> > 더불어 Issue 제목도 수정 부탁드립니다.

제가 사실 깃헙 사용법을 잘 몰라요 ^^;; 제목 수정 하긴 했는데 이러면 되는지 잘 모르겠습니다.

**Comment by kimsooyoung** [comment]
시간이 오래 지나 issue를 닫겠습니다. 윈도우 개발 과정은 wsl 사용으로 대체 강의를 제작하여 업로드하겠습니다.
